# dvc.yaml
stages:
  prepare_data:
    cmd: python src/data_prep.py
    deps:
      - src/data_prep.py
      - IMDB Dataset.csv
      - params.yaml
    outs:
      - data/train.csv
      - data/test.csv

  train_model:
    cmd: python src/train.py
    deps:
      - src/train.py
      - data/train.csv
      - data/test.csv
      - params.yaml
    params:
      - models.svm.C
      - models.svm.kernel
      - models.rf.n_estimators
      - models.rf.max_depth
      - models.lr.C
      - models.lr.solver
      - train.cv_folds
      - train.test_size
    outs:
      - models/best_model.pkl
    metrics:
      - mlruns/