# -------------------------------------------------
# GLOBAL
# -------------------------------------------------
data:
  label_column: sentiment          # IMDB
  heart_label_column: target       # Heart
preprocess:
  numeric:
    scale: true
  text:
    min_words: 4
    max_words: 1500
    max_len: 100
    oov_token: "<OOV>"
    clean_html: true
train:
  sample_size: 5000
  test_size: 0.20
  random_state: 42
  cv_folds: 3
models:
  lr:
    enabled: true
    params:
      C: [0.1, 1]
  linearsvc:
    enabled: true
    params:
      C: [0.1, 1]
  xgb:
    enabled: true
    params:
      learning_rate: [0.01, 0.2]
      max_depth: [3, 5]
      n_estimators: [5, 10]
  gbm:
    enabled: true
    params:
      learning_rate: [0.01, 0.1]
      max_depth: [3, 5]
      n_estimators: [5, 10]